version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_services
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ./mongodb_collection/navdis-website.resources.json:/app/navdis-website.resources.json
    environment:
      CONFIG_FILE: "/app/navdis-website.resources.json"

#  db:
#    image: mongo:5.0.5
#    restart: unless-stopped
#    volumes:
#      - ./data/db:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: LVTPz79DYyGQDFvyDD3XxKsDLh7NyjQ9
#      MONGO_INITDB_DATABASE: navdis-website
#    ports:
#      - 27017:27017
